### PR TITLE
Fix model:Post

### LINKED ISSUE #5: Feature: Share Post
I see that you implemented this already but I assume it doesn't work, or at least it should be improved.

**Models**
1. Why did you add `blank=True` to [Post.image](https://github.com/ozkseyma/hipogram/blob/main/hipogram/posts/models.py#L6)? Posts are meaningless if they don't have an image. Lets remove it.
2. Why did you add `null=True` to `Post.created_by`? Lets remove it too, all posts needs and authenticated creator.

**Views**
1. Anonymous users shouldn't be able to share posts, or even better, they shouldn't see the creation form. Please redirect anonymous users that click "Share a Photo" button to the **login** page.

Ignore `Like` and `Tags` features for now. You can comment out related codes and create a migration to delete related fields.

### PR DESCRIPTION
**Pull request by seymaozukanar**
Remove blank=True from Post.image and null=True from Post.created_by.
Ignore 'like_count' , 'tags' and related code.

### CODE REVIEW

**Comment by KaratasFurkan** [comment]
Looks good so far, can you please fix the template (HTML) too? Please make sure you can share a post on your local environment.

Hint: form with images needs an extra attribute.

**Comment by KaratasFurkan** [comment]
Ignore conflicts for now, we can handle them after we decided to merge this.

**Comment by seymaozukanar** [comment]
> Looks good so far, can you please fix the template (HTML) too? Please make sure you can share a post on your local environment.
> 
> Hint: form with images needs an extra attribute.

I have fixed it. Can you take a look?

**Comment by KaratasFurkan** [comment]
Looks good, thanks. Just one more small thing, you can use [crispy forms](https://github.com/django-crispy-forms/django-crispy-forms) for better form rendering. We already set it up at [here](https://github.com/ozkseyma/hipogram/blob/main/requirements.txt#L3), [here](https://github.com/ozkseyma/hipogram/blob/main/hipogram/settings.py#L43) and [here](https://github.com/ozkseyma/hipogram/blob/main/hipogram/settings.py#L145). Also there is an example usage in [here](https://github.com/ozkseyma/hipogram/blob/main/hipogram/users/templates/form_card.html#L10).

To resolve conflict, you need to remove (git rm cached) db.sqlite3 file from this branch too.

After these changes, this PR will be ready to merge.

**Comment by seymaozukanar** [comment]
> Looks good, thanks. Just one more small thing, you can use [crispy forms](https://github.com/django-crispy-forms/django-crispy-forms) for better form rendering. We already set it up at [here](https://github.com/ozkseyma/hipogram/blob/main/requirements.txt#L3), [here](https://github.com/ozkseyma/hipogram/blob/main/hipogram/settings.py#L43) and [here](https://github.com/ozkseyma/hipogram/blob/main/hipogram/settings.py#L145). Also there is an example usage in [here](https://github.com/ozkseyma/hipogram/blob/main/hipogram/users/templates/form_card.html#L10).
> 
> To resolve conflict, you need to remove (git rm cached) db.sqlite3 file from this branch too.
> 
> After these changes, this PR will be ready to merge.

I have updated the template using crispy forms. I also removed the db.sqlite3 file from this branch.

**Comment by KaratasFurkan** [comment]
I'm getting `Reverse for 'list' not found. 'list' is not a valid view function or pattern name.` Can you please test it?

**Comment by seymaozukanar** [comment]
> 
I get the same error, I am looking for ways to figure that out.

**Comment by KaratasFurkan** [comment]
Hint: check this [example](https://docs.djangoproject.com/en/3.1/topics/http/urls/#id5)

**Comment by KaratasFurkan** [comment]
Looks good, thanks :+1:

**Pull request merged**
