### PR TITLE
Add pagination to post list view

### LINKED ISSUE #13: Add pagination to the post list view
Please add pagination to [PostListView](https://github.com/ozkseyma/hipogram/blob/main/hipogram/posts/views.py#L12). This view is a class based view, you can turn it into a function based view if you are not familiar with class based views. We will eventually convert all views to class based views after a few issue later.

You can check the screenshots in the exercise PDF for UI implementation.

### PR DESCRIPTION
**Pull request by seymaozukanar**

### CODE REVIEW

**Comment by KaratasFurkan** [comment]
Media files aren't related, can you remove them? Also, they should be ignored, we changed gitignore for this, I didn't understand how they are included to version control again :thinking:

**Comment by seymaozukanar** [comment]
Everything has been taken care of. The request should be ready to be tested now.

**Comment by KaratasFurkan** [comment]
It's working well, thanks. Just one minor change, can you set the item count per page to `2`? it would be better for testing. After this change, you can merge this.

**Comment by seymaozukanar** [comment]
> It's working well, thanks. Just one minor change, can you set the item count per page to `2`? it would be better for testing. After this change, you can merge this.

Done.

**Pull request merged**
